/**
 * generated by Xtext 2.26.0
 */
package org.xtext.pascal.program.demoFkd;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>simple type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.pascal.program.demoFkd.simple_type#getSubrange <em>Subrange</em>}</li>
 *   <li>{@link org.xtext.pascal.program.demoFkd.simple_type#getEnumerated <em>Enumerated</em>}</li>
 *   <li>{@link org.xtext.pascal.program.demoFkd.simple_type#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see org.xtext.pascal.program.demoFkd.DemoFkdPackage#getsimple_type()
 * @model
 * @generated
 */
public interface simple_type extends EObject
{
  /**
   * Returns the value of the '<em><b>Subrange</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Subrange</em>' containment reference.
   * @see #setSubrange(subrange_type)
   * @see org.xtext.pascal.program.demoFkd.DemoFkdPackage#getsimple_type_Subrange()
   * @model containment="true"
   * @generated
   */
  subrange_type getSubrange();

  /**
   * Sets the value of the '{@link org.xtext.pascal.program.demoFkd.simple_type#getSubrange <em>Subrange</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Subrange</em>' containment reference.
   * @see #getSubrange()
   * @generated
   */
  void setSubrange(subrange_type value);

  /**
   * Returns the value of the '<em><b>Enumerated</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Enumerated</em>' containment reference.
   * @see #setEnumerated(enumerated_type)
   * @see org.xtext.pascal.program.demoFkd.DemoFkdPackage#getsimple_type_Enumerated()
   * @model containment="true"
   * @generated
   */
  enumerated_type getEnumerated();

  /**
   * Sets the value of the '{@link org.xtext.pascal.program.demoFkd.simple_type#getEnumerated <em>Enumerated</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Enumerated</em>' containment reference.
   * @see #getEnumerated()
   * @generated
   */
  void setEnumerated(enumerated_type value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.pascal.program.demoFkd.DemoFkdPackage#getsimple_type_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.pascal.program.demoFkd.simple_type#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

} // simple_type
