/**
 * generated by Xtext 2.26.0
 */
package org.xtext.pascal.program.demoFkd.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.pascal.program.demoFkd.DemoFkdPackage;
import org.xtext.pascal.program.demoFkd.method_part;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>method part</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class method_partImpl extends MinimalEObjectImpl.Container implements method_part
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected method_partImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DemoFkdPackage.Literals.METHOD_PART;
  }

} //method_partImpl
